### ISSUE TITLE
Update status for tr-tr on Transifex

### ISSUE THREAD

**Issue by caugner** [selcukkutuk/vue-cli-locale-tr-tr#1]
@selcukkutuk I just wanted to let you know that I have added [the `tr-tr` locale on Transifex](https://www.transifex.com/vuejs/vue-cli/language/tr_TR/) (and I have sent you an invite to be the language coordinator both for `tr` and `tr-tr`). This makes it easier to keep the locale up-to-date with the English original and allows for easier collaboration.

There are currently 104 untranslated keys for `tr-tr`, which [can be translated directly via Transifex](https://www.transifex.com/vuejs/vue-cli/translate/#tr_TR/cli-ui/148883205?q=translated%3Ano).

Afterwards, the "ready for use" JSON file can be easily exported here (click on `cli-ui` and choose `Download for use`):
https://www.transifex.com/vuejs/vue-cli/language/tr_TR/

**Comment by selcukkutuk** [comment]
It was very difficult to keep track of the changes. Thank you so much.
